# --- 吉村モデル 黄金比宇宙 ---
H0 = 72.6397
Omega_b = 0.0486
Omega_cdm = 0.2589
z_star_yoshimura = 3000.0
f_star_yoshimura = 0.135

# 出力設定
output = tCl,pCl,lCl,mPk
write background = yes
background_verbose = 1
thermodynamics_verbose = 1
